### PR TITLE
Improved cert chain mgmt

### PR DESCRIPTION
**Pull request by kelson42**
# Description

Speed-up full chain mgmt.

Fixes/addresses #26 

## Type of change

Please delete options that are not relevant.

- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ X ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ X ] Changes have been manually tested (please provide information on test platform using the fields below)

## Test / Development Platform Information

- Ubuntu 14.04
- Crypt::OpenSSL::PKCS12 vgit version
- Perl 5.24.1
- OpenSSL 1.1

### CODE REVIEW

**Comment by jonasbn** [comment]
Hi @kelson42 

Before I _plunge_ into the review - How does this PR balance with PR #25 ? :grimacing:

**Comment by kelson42** [comment]
@jonasbn Same feature/output, #25 is the first/normal implementation. This one is a "one pass" implementation - better approach but more code has changed (or being suppressed).

**Comment by jonasbn** [comment]
Sounds great, I will focus on this PR then 😄

**Comment by jonasbn** [comment]
Release 0.10 have just been uploaded to PAUSE/CPAN

**Pull request merged**
