### PR TITLE
Add trust chain support

### PR DESCRIPTION
**Pull request by kelson42**
# Description

If cert PEM includes the whole trust chain, then includes it in the P12 too.
Fixing #22.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Changes have been manually tested (please provide information on test platform using the fields below)

## Test / Development Platform Information

- Operating system and version
- Crypt::OpenSSL::PKCS12 version : git master
- Perl version : perl5 (revision 5 version 18 subversion 2)
- OpenSSL version : 1.1

### CODE REVIEW

**Comment by kelson42** [comment]
@dsully @jonasbn Current implementation respects previous approach of doing things but is a bit inefficient as we have to parse the PEM string two times to build the BIO. We should probably merge  _load_x509() and _load_ca() in one function to avoid that... but I was not bold enough to follow that path. Let me know if I should be bolder ;)

**Comment by jonasbn** [comment]
@dsully I have reviewed the changes proposed by @kelson42 and it looks good. Do you want to me to make a release. I do the release from my own fork, but the proposed changes from @kelson42 should go into the master branch. If am up for a maintainer-/commit-bit if it is okay with you.

**Comment by jonasbn** [comment]
@kelson42 Your suggestion on the merge of `_load_x509()` and `_load_ca()` sounds like a good idea. A PR could demonstrate how it could/should work. @dsully what do you think?

**Comment by dsully** [comment]
Merging those functions seems like a reasonable approach.

**Comment by jonasbn** [comment]
My c reviewing skills are not particular sharp, but there is only one way to learn, it will take some time for me to review this contribution. But I will see if we can squeeze it into the release going out later tonight.

**Comment by kelson42** [comment]
@jonasbn @dsully I could have a look tomorrow.

**Comment by jonasbn** [comment]
@kelson42 don't sweat it - take your time. Your PRs are most appreciated, but we are all volunteers...

**Comment by kelson42** [comment]
@jonasbn No problem. In this case, I need to fix that for a client. Happy to work on the PR, in particular if you can release a new version on cpan.org in the next few weeks :)

**Comment by jonasbn** [comment]
Hi @kelson42 

I will have a look at your original PR and will do a review of the code. Please open a new PR for the next improvement.

**Comment by jonasbn** [comment]
@kelson42 just for your information. @dsully is the original author, but I will do my best to help improving and releasing the distribution. My situation is simply that we use PKCS12 at work and we want to contribute to continuous stability and improvement. @dsully has been so kind as to give me co-maintainership on PAUSE so I could assist with the shipping and now commit rights to the repository, so I can assist with processing PRs, issues and doing general open source yak-shaving 

Thanks for the trust @dsully 👍

**Comment by jonasbn** [comment]
@kelson42 I have approved PR #27, so I guess this PR can just be closed?

**Comment by kelson42** [comment]
@jonasbn yes. Thx.

**Pull request closed without merging**
