### PR TITLE
New method create_as_string to create a PKCS12 string

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description

New method create_as_string

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Changes have been manually tested (please provide information on test platform using the fields below)

## Test / Development Platform Information

- Operating system Centos 8
- Crypt::OpenSSL::PKCS12 version 1.7
- Perl version v5.26.3
- OpenSSL version 1.1.1g

### CODE REVIEW

**Review by jonasbn — COMMENTED** [review]
Hi @jrouzierinverse

This PR clashes with PR #37 so until that is sorted out, this PR will be pending.

**Comment by jrouzierinverse** [comment]
> Hi @jrouzierinverse
> 
> This PR clashes with PR #37 so until that is sorted out, this PR will be pending.

I removed the conflict.

**Comment by jrouzierinverse** [comment]
I will rebase when #37 is merged.

**Comment by jonasbn** [comment]
@jrouzierinverse I will review when you have rebased, so please ping me

**Comment by jrouzierinverse** [comment]
rebased

**Review by jonasbn — APPROVED** [review]
Looks good, I will make some updates to the documentation before releasing this.

Thanks @jrouzierinverse

**Pull request merged**
