### PR TITLE
Minor improvement to Travis integration

### PR DESCRIPTION
**Pull request by jonasbn**
I have implemented some minor improvement to the Travis integration. The CPAN client integration was broken when attempting to select the region of the mirror. The new configuration avoids this pitfall and uses the Perl Travis helper.

Unfortunately this demonstrate an issue building under perl 5.8.8, where 5.10, 5.20 and 5.26 works.

```
cc -c  -I/usr/local/opt/openssl/include -I/usr/include/openssl -I/usr/local/include/ssl -I/usr/local/ssl/include -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -Wall -Werror   -DVERSION=\"0.7\" -DXS_VERSION=\"0.7\" -fpic "-I/home/travis/perl5/perlbrew/perls/5.8/lib/5.8.8/x86_64-linux/CORE"   PKCS12.c
PKCS12.xs: In function ‘dump_certs_pkeys_bag’:
PKCS12.xs:164:7: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
       PKCS8_PRIV_KEY_INFO *cp8;
       ^
PKCS12.xs:182:7: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
       PKCS8_PRIV_KEY_INFO *p8;
       ^
cc1: all warnings being treated as errors
make: *** [PKCS12.o] Error 1
/home/travis/travis-perl-helpers/init: line 123: [: : integer expression expected
```

Perhaps this is more obvious to you what the problem might be.

Ref: https://travis-ci.org/jonasbn/perl-crypt-openssl-pkcs12/jobs/284337128

### CODE REVIEW

**Comment by dsully** [comment]
Checks are failing..

**Comment by jonasbn** [comment]
Hi @dsully 

They passed before? - I kept observing issues for 5.8.8 for my fork. First related to the CPAN client, which I then tried to address, uncovering the mentioned compilation error. I will revisit my branch to see if I can spot any issues in regard to the compilation error, if you do not observe these in master. My fork should be updated from your master, unless I did something wrong.

I will get back to you ASAP.

**Comment by jonasbn** [comment]
Hi @dsully 

I checked the previous Travis run (https://travis-ci.org/dsully/perl-crypt-openssl-pkcs12/jobs/249108319) from my initial change set integrating Travis, it also failed. I can however not retrieve the detailed report 👎 

I have looked at the CPANTesters reports and it does not seem as if there has been much success after the release of 0.5.

- 0.7 http://matrix.cpantesters.org/?dist=Crypt-OpenSSL-PKCS12+0.7
- 0.6 http://matrix.cpantesters.org/?dist=Crypt-OpenSSL-PKCS12%200.6
- 0.5 http://matrix.cpantesters.org/?dist=Crypt-OpenSSL-PKCS12%200.5

I will investigate the compilation error related to 5.8.8, which seems like the best shot at getting somewhere right now.

**Comment by jonasbn** [comment]
Just installed 5.8.9 using perlbrew, build succeeds.

**Comment by jonasbn** [comment]
Oh man, I am on MacOS, the issue demonstrated by Travis is on Linux, I will try to see if I can reproduce on Linux.

**Comment by jonasbn** [comment]
Hi @dsully,

I wanted to get the Travis integration working without altering the actual source code of the product BUT this was not possible, so this PR does a little more than I intended.

I decided to focus on the build failure on 5.8.8. I got a Docker setup running, but it did not demonstrate the issue. I dug into the actual error:

> ISO C90 forbids mixed declarations and code

It seem to be triggered by:  `[-Werror=declaration-after-statement]`. It seems to be a **C90** thing and a solution is described [here](https://stackoverflow.com/questions/13291353/iso-c90-forbids-mixed-declarations-and-code-in-c).

This hinted at changes to the source code, so I examined the existing changes in this region:

https://github.com/dsully/perl-crypt-openssl-pkcs12/blame/master/PKCS12.xs#L155

And it seems as if the:

> Modifications for compatibility with OpenSSL 1.1.0 

Actually made the structure weird, I shifted the code around as pointed out by the StackOverflow post and now everything works. I decided to reuse the `p8` variable and eliminated the `cp8` variable. This could break something, so please review the change before merging.

**Pull request merged**
